New article/natserract
teknologi-umum/blog pull request #102
Opened 2022-06-05 12:53 UTC by natserract

New article: elixir pattern match, assignment & immutability

2022-06-05 13:51 UTC, elianiva requested changes
nice, cuma ada beberapa typo/stylistic changes

btw, yarn.lock hapus aja, udah ada package-lock.json

2022-06-05 13:51 UTC, elianiva commented on content/elixir-assignment.md
> +[Elixir](https://github.com/elixir-lang/elixir) adalah bahasa pemrogaman fungsional, dinamis, dan metaprogrammable dibangun untuk membuat aplikasi yang scalable dan maintanable. Elixir dibangun dari
lebih prefer kalo istilah yg kaya gini ga perlu ditranslate

```suggestion
[Elixir](https://github.com/elixir-lang/elixir) adalah bahasa pemrograman fungsional, dinamis, dan _metaprogrammable_ dibangun untuk membuat aplikasi yang scalable dan maintanable. Elixir dibangun dari bahasa pemrogaman [Erlang](https://www.erlang.org/), secara bersamaan bahasa ini melakukan pendekatan [actor based](https://www.oreilly.com/library/view/functional-programming-a/9781680502756/f_0061.xhtml) untuk masalah **concurrency** dengan syntax yang lebih sederhana, clean, namun kuat.
```

2022-06-05 13:51 UTC, elianiva commented on content/elixir-assignment.md
> +Jika Anda mulai belajar Elixir, tentunya Anda akan bertemu dengan pernyataan yang sedikit membingungkan di Elixir, disana disebut bahwa Elixir tidak memiliki operator assignment `=`. Maka dari itu di
```suggestion
Jika Anda mulai belajar Elixir, tentunya Anda akan bertemu dengan pernyataan yang sedikit membingungkan di Elixir, disana disebut bahwa Elixir tidak memiliki operator assignment `=`. Maka dari itu disini kita coba kupas secara mendetail bagaimana pernyataan aneh tersebut menjadi sesuatu yang kita bisa pahami bagaimana itu bekerja.
```

2022-06-05 13:51 UTC, elianiva commented on content/elixir-assignment.md
> +In a nutshell, pattern matching adalah pola untuk membandingkan suatu data dengan struktur pola tertentu. Cara ini digunakan di banyak bahasa pemrogaman. Dalam kutipan artikel [Wikipedia](https://en.
```suggestion
In a nutshell, pattern matching adalah pola untuk membandingkan suatu data dengan struktur pola tertentu. Cara ini digunakan di banyak bahasa pemrogaman. Dalam kutipan artikel [Wikipedia](https://en.wikipedia.org/wiki/SNOBOL), pattern matching pertama kali digunakan pada [SNOBOL(1962)](http://www.snobol4.org/docs/burks/tutorial/ch4.htm) yang digunakan untuk operasi string. Di masa modern kini, fitur ini banyak digunakan seperti di bahasa pemrograman seperti OCaml, ML, Rust, Haskell, etc.
```

2022-06-05 13:51 UTC, elianiva commented on content/elixir-assignment.md
> +```bash
```suggestion
```rust
```

2022-06-05 13:51 UTC, elianiva commented on content/elixir-assignment.md
> +Itu adalah code yang simple, di bahasa pemrogaman seperti javascript itu terlihat seperti operasi [assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Assignment)
```suggestion
Itu adalah contoh kode yang sederhana, di bahasa pemrograman seperti Javascript itu terlihat seperti operasi [assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Assignment) (`=`) nilai pada sebuah variabel. Namun ketika di Elixir, itu adalah hal yang berbeda. Di Elixir, operator `=` bukanlah operator assignment melainkan _match operator_ atau bisa juga disebut _binding_.
```

2022-06-05 13:51 UTC, elianiva commented on content/elixir-assignment.md
> +Dalam elixir, apapun adalah ekspresi, dan setiap ekspresi memiliki hasil. Artinya, dalam case diatas hasilnya adalah apapun yang ada disebelah kanan operator `=` yaitu `1`, `2`. Jadi **ketika mendekl
```suggestion
Dalam Elixir, apapun adalah ekspresi, dan setiap ekspresi memiliki hasil. Artinya, dalam case diatas hasilnya adalah apapun yang ada disebelah kanan operator `=` yaitu `1`, `2`. Jadi **ketika mendeklarasikan variabel dengan nilai, maka variabel tersebut sudah menjadi milik nilai itu**. Lalu antara nilai dengan variabel **di-evaluasi / di-check jika itu cocok/sama** maka hasil terakhirnya selesai dievaluasi.
```

2022-06-05 13:51 UTC, elianiva commented on content/elixir-assignment.md
> +Anda lihat? pada bagian operasi pertama `num = 10`, proses yang terjadi yakni:
```suggestion
Anda lihat? Pada bagian operasi pertama `num = 10`, proses yang terjadi yakni:
```

2022-06-05 13:51 UTC, elianiva commented on content/elixir-assignment.md
> +- Saat coba dicocokan nilai yang lain, `5 = num` dan itu sudah exists. Maka artinya 5 tidak sama dengan 10 dan tentunya `match error`.
```suggestion
- Saat coba dicocokkan dengan nilai yang lain, `5 = num` dan itu sudah exists. Maka artinya 5 tidak sama dengan 10 dan tentunya `match error`.
```

2022-06-05 13:51 UTC, elianiva commented on content/elixir-assignment.md
> +Itu sebenernya seperti kondisi biasa, jika _num == 10_ maka cetak!
```suggestion
Itu sebenarnya seperti kondisi biasa, jika _num == 10_ maka cetak!
```

2022-06-05 13:51 UTC, elianiva commented on content/elixir-assignment.md
> +- (`!`): Fungsi atau makro di mana kasus kegagalan memunculkan pengecualian.
```suggestion
- (`!`): Fungsi atau makro di mana kasus kegagalan memunculkan exception.
```

2022-06-05 13:51 UTC, elianiva commented on content/elixir-assignment.md
> +Bind secara sederhana, **mengaitkan/memberi nama dengan suatu nilai atau fungsi**. Di elixir, binding dilakukan dengan operator `=`, disebelah kanan adalah ekspresi, disebelah kiri adalah namanya. Bi
```suggestion
Bind secara sederhana, **mengaitkan/memberi nama dengan suatu nilai atau fungsi**. Di Elixir, binding dilakukan dengan operator `=`, disebelah kanan adalah ekspresi, disebelah kiri adalah namanya. Bind dilakukan untuk **mereferensikan suatu istilah (variabel) ke dalam memori**. Jadi ketika membuat variabel, itu secara tidak langsung menjadikan nama variabel tersebut menjadi referensi dari memori.
```

2022-06-05 13:51 UTC, elianiva commented on content/elixir-assignment.md
> +Secara default semua data di Elixir bersifat [immutable](https://en.wikipedia.org/wiki/Immutable_object). Artinya, yang dilakukan pada operasi diatas bukanlah merubah nilai `num` menjadi `20`, melain
```suggestion
Secara default semua data di Elixir bersifat [immutable](https://en.wikipedia.org/wiki/Immutable_object). Artinya, yang dilakukan pada operasi diatas bukanlah merubah nilai `num` menjadi `20`, melainkan rebinding `num` dengan `20`. Rebinding di Elixir **tidak mengubah nilai aslinya**. Tetapi **membuat memori baru dan menetapkan nama ke lokasi memori yang baru**. Jadi ketika rebind dilakukan, istilah (variabel) tersebut akan mengambil referensi ke lokasi memori yang berbeda. Ini berkaitan dengan [manajemen memori](https://www.honeybadger.io/blog/elixir-memory-structure/) (allocations) di Elixir.
```

2022-06-05 13:51 UTC, elianiva commented on content/elixir-assignment.md
> +Nantinya, hasil evaluasi akan disimpan di lokasi memori lain. Jadi jika ingin me-modifikasi input tidak mengubah inputan aslinya, tetapi melalui beberapa penyalinan data. Coba lihat contoh ini:
```suggestion
Nantinya hasil evaluasi akan disimpan di lokasi memori lain. Jadi ketika kita me-modifikasi input maka hal itu tidak akan mengubah inputan aslinya, tetapi akan melalui beberapa penyalinan data. Coba lihat contoh ini:
```

2022-06-05 13:51 UTC, elianiva commented on content/elixir-assignment.md
> +Lists di elixir disimpan sebagai [linked list](https://www.educative.io/edpresso/what-is-a-linked-list) dimana setiap data (nodes) saling berhubungan dengan node berikutnya. Node pertama disebut kepa
```suggestion
List di Elixir disimpan sebagai [linked list](https://www.educative.io/edpresso/what-is-a-linked-list) dimana setiap data (nodes) saling berhubungan dengan node berikutnya. Node pertama disebut kepala (`head`) dan terakhir disebut ekor (`tail`):
```

2022-06-05 13:51 UTC, elianiva commented on content/elixir-assignment.md
> +`String.capitalize()`, mengonversi karakter pertama dalam string menjadi huruf besar dan sisanya menjadi huruf kecil menurut mode (e.g. `:default`).
```suggestion
`String.capitalize()` mengkonversi karakter pertama dalam string menjadi huruf besar dan sisanya menjadi huruf kecil menurut mode (e.g. `:default`).
```

2022-06-05 13:51 UTC, elianiva commented on content/elixir-assignment.md
> +> **Inti fokus dari pemrogaman fungsional adalah untuk konsistensi dan keamanan data. Sedangkan [OOP](https://www.techtarget.com/searchapparchitecture/definition/object-oriented-programming-OOP) send
```suggestion
> **Inti fokus dari pemrogaman fungsional adalah untuk konsistensi dan keamanan data. Sedangkan [OOP](https://www.techtarget.com/searchapparchitecture/definition/object-oriented-programming-OOP) sendiri lebih fokus untuk manufaktur (arsitektur) dan desain suatu aplikasi**. Meskipun kedua paradigma ini bisa untuk dua alasan diatas, itu adalah murni pendapat saya. _So every people can make own decision right?_
```

2022-06-05 14:10 UTC, natserract commented
Thankyou for review @elianiva, updated ya please check again.

2022-06-05 14:26 UTC, elianiva approved these changes
sip, jangan lupa hapus yarn.lock nanti

2022-06-08 13:10 UTC, aldy505 approved these changes

2022-06-10 16:11 UTC, merged