[wip] fix(frontend) : resolve card
teknologi-umum/blog pull request #119
Opened 2022-10-03 14:59 UTC by arnoldart

2022-10-05 05:56 UTC, elianiva commented
ada conflict

2022-10-05 05:56 UTC, elianiva requested changes
scrollbarnya jangan diilangin, atau kasih indicator kalo topicsnya itu bisa discroll, kalo gini jadi ngga tau kalo topicsnya itu sebenernya ada banyak

2022-10-05 06:39 UTC, arnoldart commented
> scrollbarnya jangan diilangin, atau kasih indicator kalo topicsnya itu bisa discroll, kalo gini jadi ngga tau kalo topicsnya itu sebenernya ada banyak

Ok

2022-10-05 23:55 UTC, arnoldart commented
Note : scroll baru untuk firefox

2022-10-06 03:23 UTC, elianiva commented
![image](https://user-images.githubusercontent.com/51877647/194206936-4e2eac5e-b67f-48fc-890a-149020038790.png)

ini scrollbarnya dimunculin pas lagi dihover aja, abis itu sebelah kanan kasih fade biar ngga langsung kepotong gitu yg ga muat

2022-12-07 08:00 UTC, herlangga72 commented
kurang gradient colornya..

2023-07-02 13:43 UTC, lamualfa commented
https://github.com/teknologi-umum/blog/pull/120#issuecomment-1616665771

2023-07-02 13:43 UTC, closed without merging