refactor: tidy up some old code
teknologi-umum/blog pull request #138
Opened 2023-06-11 15:07 UTC by elianiva

- use pnpm instead of npm
- changed indent style from 2 to 4 to make it look less cluttered
- extract prop typings into its own separate type definition
- dedupe type definition
- remove props destructuring since it makes it less clear if a value comes from props
- fix hydration mismatch when rendering caused by figure nested inside p
- safer null/undefined check by enforcing the value to be boolean
- added missing type annotations in some components
- updated svgr config according to docs

2023-06-11 15:18 UTC, aldy505 approved these changes

2023-06-11 15:18 UTC, aldy505 commented on .github/workflows/ci.yml
> +              uses: actions/checkout@v2
```suggestion
              uses: actions/checkout@v3
```

2023-06-11 15:18 UTC, aldy505 commented on .github/workflows/ci.yml
> +              run: npm install
ini ga sekalian diubah ke pnpm?

2023-06-11 15:18 UTC, aldy505 commented on package.json
> +        "next": "^13.4.5",
mantap

2023-06-11 15:18 UTC, aldy505 commented on package.json
> +        "shiki": "0.14.2",
kalo dua ini di bump, polarite harus di urus juga ini.

2023-06-11 15:18 UTC, aldy505 commented on package.json
> +        "shiki": "0.14.2",
weekend depan deh gw sentuh

2023-06-11 15:18 UTC, aldy505 commented on utils/transformMdx.ts
> +} satisfies Partial<Options>;
anjay

2023-06-11 16:01 UTC, krowter commented on components/ImageWithFrame.tsx
> +            <img className="inline-block p-0 overflow-hidden rounded-md" src={props.src} alt={props.alt ?? "-"} />
fallback buat `alt`nya empty string aja mending
https://www.w3.org/WAI/tutorials/images/decorative/

2023-06-11 16:05 UTC, krowter commented on components/ReadAnyway.tsx
> +                    FIND MORE POST
Mintol casing nya diubah kayak biasa, terus className `uppercase`, biar ngga dieja satu2 sama screenreader

2023-06-12 04:19 UTC, aldy505 commented on package.json
> +        "shiki": "0.14.2",
KOK POLARITE. harusnya graphene.

2023-06-17 11:17 UTC, aldy505 commented
Should bump to Node 20

2023-06-18 09:57 UTC, aldy505 commented
Some issues with this PR:

1. GitHub actions workflow error:
    [Invalid workflow file: .github/workflows/ci.yml#L38](https://github.com/teknologi-umum/blog/actions/runs/5301580643/workflow)
    The workflow is not valid. .github/workflows/ci.yml (Line: 38, Col: 20): Unexpected value '' .github/workflows/ci.yml (Line: 39, Col: 15): Unexpected value 'path'
2. Netlify build error: (see https://app.netlify.com/sites/teknum/deploys/648e7a802b726c00074b6a53)
```
10:31:54 AM: Netlify Build                                                 
10:31:54 AM: ────────────────────────────────────────────────────────────────
10:31:54 AM: ​
10:31:54 AM: ❯ Version
10:31:54 AM:   @netlify/build 29.12.1
10:31:54 AM: ​
10:31:54 AM: ❯ Flags
10:31:54 AM:   baseRelDir: true
10:31:54 AM:   buildId: 648e7a802b726c00074b6a51
10:31:54 AM:   deployId: 648e7a802b726c00074b6a53
10:31:54 AM: ​
10:31:54 AM: ❯ Current directory
10:31:54 AM:   /opt/build/repo
10:31:54 AM: ​
10:31:54 AM: ❯ Config file
10:31:54 AM:   /opt/build/repo/netlify.toml
10:31:54 AM: ​
10:31:54 AM: ❯ Context
10:31:54 AM:   deploy-preview
10:31:54 AM: ​
10:31:54 AM: ❯ Using Next.js Runtime - v3.9.2
10:31:54 AM: ​
10:31:54 AM: ❯ Outdated plugins
10:31:54 AM:    - @netlify/plugin-nextjs@3.9.2: latest version is 4.37.4
10:31:54 AM:      To upgrade this plugin, please uninstall and re-install it from the Netlify plugins directory (https://app.netlify.com/plugins)
10:31:55 AM: ​
10:31:55 AM: @netlify/plugin-nextjs (onPreBuild event)                     
10:31:55 AM: ────────────────────────────────────────────────────────────────
10:31:55 AM: ​
10:31:55 AM: Using Next.js 13.4.6
10:31:55 AM: Warning: support for Next.js >=11.1.0 is experimental
10:31:55 AM: NOTE: Static HTML export Next.js projects (projects that use `next export`) do not require most of this plugin. For these sites, this plugin *only* caches builds.
10:31:55 AM: ​
10:31:55 AM: (@netlify/plugin-nextjs onPreBuild completed in 9ms)
10:31:55 AM: ​
10:31:55 AM: build.command from netlify.toml                               
10:31:55 AM: ────────────────────────────────────────────────────────────────
10:31:55 AM: ​
10:31:55 AM: $ npm run build && npm run export
10:31:55 AM: > teknum-blog@0.1.0 build
10:31:55 AM: > next build
10:31:56 AM: - warn No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
10:31:56 AM: - info Linting and checking validity of types...
10:31:58 AM: - info Creating an optimized production build...
10:32:10 AM: Failed to compile.
10:32:10 AM: 
10:32:10 AM: ./services/post-by-slug.ts
10:32:10 AM: Module not found: Can't resolve 'fs/promises'
10:32:10 AM: https://nextjs.org/docs/messages/module-not-found
10:32:10 AM: Import trace for requested module:
10:32:10 AM: ./services/index.ts
10:32:10 AM: ./pages/search.tsx
10:32:10 AM: ./services/post-slugs.ts
10:32:10 AM: Module not found: Can't resolve 'fs/promises'
10:32:10 AM: https://nextjs.org/docs/messages/module-not-found
10:32:10 AM: Import trace for requested module:
10:32:10 AM: ./services/index.ts
10:32:10 AM: ./pages/search.tsx
10:32:10 AM: > Build failed because of webpack errors
10:32:11 AM: ​
10:32:11 AM: "build.command" failed                                        
10:32:11 AM: ────────────────────────────────────────────────────────────────
10:32:11 AM: ​
10:32:11 AM:   Error message
10:32:11 AM:   Command failed with exit code 1: npm run build && npm run export (https://ntl.fyi/exit-code-1)
10:32:11 AM: ​
10:32:11 AM:   Error location
10:32:11 AM:   In build.command from netlify.toml:
10:32:11 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
10:32:11 AM:   npm run build && npm run export
10:32:11 AM: ​
10:32:11 AM:   Resolved config
10:32:11 AM:   build:
10:32:11 AM:     base: /opt/build/repo
10:32:11 AM:     command: npm run build && npm run export
10:32:11 AM:     commandOrigin: config
10:32:11 AM:     environment:
10:32:11 AM:       - REVIEW_ID
10:32:11 AM:     publish: /opt/build/repo/out
10:32:11 AM:     publishOrigin: config
10:32:11 AM:   plugins:
10:32:11 AM:     - inputs: {}
10:32:11 AM:       origin: ui
10:32:11 AM:       package: '@netlify/plugin-nextjs'
10:32:11 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
10:32:11 AM: Failing build: Failed to build site
10:32:12 AM: Finished processing build request in 58.313s
```

2023-06-24 23:43 UTC, aldy505 commented
@elianiva the build still failed

2023-06-26 07:42 UTC, elianiva commented
ga ngerti apa yg salah sama netlify, di local bisa, mau cek ga punya akses netlify

2023-06-26 08:07 UTC, aldy505 commented
minta akses ke @lamualfa dia yang punya akun kalo gasalah

2023-06-26 09:59 UTC, lamualfa commented
`@netlify/plugin-nextjs` harus diupdate dulu.

2023-06-26 13:50 UTC, elianiva commented
> `@netlify/plugin-nextjs` harus diupdate dulu.

tapi kita ngga pake itu

2023-06-26 14:48 UTC, aldy505 commented
might be relevant: https://github.com/vercel/next.js/discussions/34992

I don't know for sure though, I don't code in next

2023-06-27 06:51 UTC, lamualfa commented
Pluginnya udah gw update tapi masih error di `fs/promises`.

2023-06-27 06:52 UTC, lamualfa requested changes

2023-06-27 06:52 UTC, lamualfa commented on next.config.js
> -      fs: false,
Ini dibalikin lagi biar nggak error.

2023-06-27 12:08 UTC, aldy505 commented on next.config.js
> -      fs: false,
@elianiva ikuti perintah lord kita

2023-07-01 11:30 UTC, lamualfa requested changes
https://github.com/teknologi-umum/blog/blob/7860e27cb6a24648cee967d69fd81c54016ee604/netlify.toml#L3

Publish directorynya dihapus biar nggak error.

2023-07-02 13:36 UTC, lamualfa approved these changes

2023-07-02 13:37 UTC, merged