Ini PR
teknologi-umum/blog pull request #143
Opened 2023-08-13 03:51 UTC by kawaii-ghost

Tinggalkan komentar

2023-08-13 03:55 UTC, aldy505 commented
@kawaii-ghost CI failed. Jalanin `pnpm run format` dulu.

2023-08-16 05:31 UTC, aldy505 commented
@elianiva can you help on executing `pnpm run format` please?

2023-08-17 11:40 UTC, elianiva commented
anu, ga bisa push langsung karena branchnya di repo @kawaii-ghost
but dw i have a solution

2023-08-17 11:40 UTC, elianiva requested changes
langsung add suggestion to batch aja

2023-08-17 11:40 UTC, elianiva commented on .github/CODE_OF_CONDUCT.md
> +  community
```suggestion
-   Demonstrating empathy and kindness toward other people
-   Being respectful of differing opinions, viewpoints, and experiences
-   Giving and gracefully accepting constructive feedback
-   Accepting responsibility and apologizing to those affected by our mistakes,
    and learning from the experience
-   Focusing on what is best not just for us as individuals, but for the overall
    community
```

2023-08-17 11:40 UTC, elianiva commented on .github/CODE_OF_CONDUCT.md
> +  professional setting
```suggestion
-   The use of sexualized language or imagery, and sexual attention or advances of
    any kind
-   Trolling, insulting or derogatory comments, and personal or political attacks
-   Public or private harassment
-   Publishing others' private information, such as a physical or email address,
    without their explicit permission
-   Other conduct which could reasonably be considered inappropriate in a
    professional setting
```

2023-08-17 11:40 UTC, elianiva commented on .github/CODE_OF_CONDUCT.md
> +# Contributor Covenant Code of Conduct
```suggestion
# Contributor Covenant Code of Conduct
```

2023-08-17 11:46 UTC, herlangga72 commented
Biasa pada lupa prettier. Apa masukin ke build process aja??

2023-08-17 13:05 UTC, elianiva approved these changes

2023-08-17 13:05 UTC, elianiva commented
thanks

2023-08-17 13:05 UTC, merged