merge request for searching functionality
teknologi-umum/blog pull request #23
Opened 2021-08-31 20:52 UTC by rubichandrap

- fixed PostCard Component not centered at media <430px
- added search functionality
- added active class to nav links when router path is equal with the mapped routes
- added hooks useDebounce

2021-08-31 21:47 UTC, elianiva requested changes

2021-08-31 21:47 UTC, elianiva commented on hooks/useDebounce.ts
> +export default useDebounce;
prefer named export kalo helper/hooks/sejenisnya

2021-08-31 21:47 UTC, elianiva commented on hooks/index.ts
> +export { default as useDebounce } from './useDebounce';
ditto

2021-08-31 21:47 UTC, elianiva commented on components/Navbar.tsx
> +import React from 'react';
ini buat apa? bukannya udah otomatis ditambahin sama nextjs?

2021-08-31 21:47 UTC, elianiva commented on pages/search.tsx
> +import React, { useEffect, useState } from 'react';
ditto

2021-08-31 21:47 UTC, elianiva commented on pages/search.tsx
> +      console.log(json.data);
lupa belum dihapus om?

2021-08-31 21:47 UTC, elianiva commented on pages/search.tsx
> +          border-bottom-width: 1px;
ada alasan tertentu ngga pake `border-b-1` punya tailwind?

2021-08-31 21:57 UTC, rubichandrap commented on components/Navbar.tsx
> +import React from 'react';
Itu dipake buat typing, React.KeyboardEvent

2021-08-31 21:58 UTC, rubichandrap commented on hooks/useDebounce.ts
> +export default useDebounce;
Udah saya bikin aggregatornya, tp kalo ttp named ya gpp

2021-08-31 21:58 UTC, rubichandrap commented on pages/search.tsx
> +      console.log(json.data);
Lupa

2021-08-31 21:59 UTC, rubichandrap commented on pages/search.tsx
> +          border-bottom-width: 1px;
Ga ada autocompletenya tadi, jadi saya pikir ga ada

2021-08-31 22:54 UTC, elianiva approved these changes
Thanks!

![image](https://user-images.githubusercontent.com/51877647/131586050-672a2cd7-c884-4a1f-8bfe-65a4bd20fd38.png)

2021-09-01 02:49 UTC, aldy505 approved these changes
I don't have any idea what the code does. But it looks good to me.

2021-09-01 06:59 UTC, aldy505 commented
laode approved via telegram. let's merge this.

2021-09-01 06:59 UTC, merged