add new content about definition vim
teknologi-umum/blog pull request #86
Opened 2022-02-04 15:23 UTC by afman42

2022-02-04 17:38 UTC, aldy505 commented
jalanin `npm run format` dulu, biar checks nya passing

2022-02-05 03:03 UTC, afman42 commented
Apakah jalan kan di local terus commit lagi?

2022-02-05 03:20 UTC, afman42 commented
sudah ya om @aldy505

2022-02-05 05:43 UTC, aldy505 reviewed
sebenernya masih banyak typo dalam besar-kecil huruf dan titik-spasi.

contoh:
- awal kalimat masih huruf kecil
- nggak ada spasi kalau ada koma atau titik (_...setting vim muncul.Ada beberapa Mode yaitu Normal Mode,Insert Mode, Visual Mode.lalu..._)

kalo soal konten, aku nggak paham vim, jadi mari kita serahkan ke @elianiva

2022-02-05 05:43 UTC, aldy505 commented on content/apa-itu-vim-secara-singkat.md
> +Vim dikenal text editor di terminal dengan distribusi di sistem operasi windows,macos,dan linux. Aplikasi nya ringan dengan sekitar `~10mb` dan website nya pun belum berubah. Apakah vim powerfull unt
```suggestion
Vim dikenal text editor di terminal dengan distribusi di sistem operasi windows,macos,dan linux. Aplikasi nya ringan dengan sekitar `~10mb` dan website nya pun belum berubah. Apakah vim powerful untuk digunakan ? ya tergantung pengguna / pemakai bisa dijadikan IDE (Integrated Development Environment). Vim ada dua versi tampilan yaitu tampilan Grafis atau tampilan terminal
```

2022-02-05 07:32 UTC, ronnygunawan requested changes

2022-02-05 09:45 UTC, elianiva requested changes

2022-02-05 09:45 UTC, elianiva commented on content/apa-itu-vim-secara-singkat.md
> +Vim dikenal text editor di terminal dengan distribusi di sistem operasi windows,macos,dan linux. Aplikasi nya ringan dengan sekitar `~10mb` dan website nya pun belum berubah. Apakah vim powerfull unt
```suggestion
Vim dikenal sebagai text editor yang dapat berjalan pada sistem operasi Windows, MacOS, Linux, [dan lain sebagainya](https://en.wikipedia.org/wiki/Vim_(text_editor)#Availability). Aplikasi ini relatif ringan dibandingkan text editor lainnya. Apakah Vim powerful untuk digunakan? Hal ini sangat bergantung pada penggunanya. Vim dapat dijadikan sebagai Integrated Development Environment (IDE) atau sebatas Text Editor sederhana. Vim memiliki dua jenis tampilan yaitu Graphical User Interface (GUI) atau Terminal User Interface (TUI)
```

2022-02-05 09:45 UTC, elianiva commented on content/apa-itu-vim-secara-singkat.md
> +## Unduh Aplikasi [Vim](https://www.vim.org/download.php)
jangan taruh URL di heading

```suggestion
## Instalasi Vim
```

2022-02-05 09:45 UTC, elianiva commented on content/apa-itu-vim-secara-singkat.md
> +- Macos: bisa menggunakan unduh aplikasi atau pun mengetik di terminal
```suggestion
Terdapat beberapa cara untuk memasang Vim pada mesin kalian. 

- Windows

    Kalian dapat mengunduh Vim melalui [website resminya](https://www.vim.org/download.php) lalu memasangnya seperti biasa. Kalian bisa juga menggunakan package manager seperti [chocolatey](https://community.chocolatey.org/packages/vim) atau [winget](https://winget.run/pkg/vim/vim)
- Linux

    Kalian dapat menggunakan package manager yang sudah tersedia pada distribusi masing masing. Biasanya Vim sudah terpasang secara _default_, namun apabila tidak ada, kalian dapat memasangnya dengan cara seperti ini: 
    ```bash
    # ubuntu / debian / distribusi lain yang menggunakan apt
    sudo apt install vim
    
    # arch / manjaro / distribusi lain yang menggunakan pacman
    sudo pacman -S vim
    
    # fedora / distribusi lain yang menggunakan dnf
    sudo dnf install vim
    ```
    
- Mac OS
    
    Kalian dapat mengunduhnya melalui [website resmi Vim](https://www.vim.org/download.php)) atau menggunakan package manager yang ada pada Mac OS seperti [Homebrew](https://brew.sh/)
```

2022-02-05 09:45 UTC, elianiva commented on content/apa-itu-vim-secara-singkat.md
> +Ketika berada di aplikasi terminal dan sudah menginstal vim, bisa mengetik `vim` lalu `enter`
kalo `<kbd></kbd>` ga keluar stylingnya, nanti aku benerin

```suggestion
## Pengoperasian atau Penggunaanya

Ketika kalian berada di dalam terminal emulator dan sudah memasang Vim, kalian bisa langsung mengetik `vim` lalu tekan tombol <kbd>enter</kbd> untuk membukanya.
```

2022-02-05 09:45 UTC, elianiva commented on content/apa-itu-vim-secara-singkat.md
> +
```suggestion

Kalian bisa juga melakukan `vim nama_file` untuk membuka file tersebut dengan Vim. Contoh:
```

2022-02-05 09:45 UTC, elianiva commented on content/apa-itu-vim-secara-singkat.md
> +dan jika sudah berada vim, dengan mengetik apapun tidak memunculkan sesuatu kecuali keymap udah di setting vim muncul.Ada beberapa Mode yaitu Normal Mode,Insert Mode, Visual Mode.lalu mengetikan `i`
```suggestion
Jika kalian sudah berada di dalam Vim, kalian akan sadar bahwa apabila kalian mulai mengetik, tidak ada huruf yang keluar seperti layaknya text editor biasanya. Vim menggunakan prinsip _Modal Editing_ yang berarti Vim memiliki beberapa _mode_ untuk melakukan text editing. Beberapa diantaranya yaitu Normal, Insert, Visual, [dan masih banyak lagi](http://vimdoc.sourceforge.net/htmldoc/intro.html#vim-modes-intro). Untuk masuk ke dalam Insert Mode, kalian bisa menekan <kbd>i</kbd> yang berarti _insert_ atau <kbd>a</kbd> yang berarti _append_.
```

2022-02-05 09:45 UTC, elianiva commented on content/apa-itu-vim-secara-singkat.md
> +copy satu baris maka diperlukan `yy` dan jika paste diperlukan `p`. untuk menyimpan atau save file maka perlu `Shift+:` dan `w` atau pun dari keluar vim bisa menggunkan `:q`
```suggestion

### Insert Mode

Seperti yang sudah saya katakan, kalian dapat menekan <kbd>i</kbd> atau <kbd>a</kbd> untuk masuk ke dalam Insert Mode. Pada mode ini kalian dapat mengetik apapun yang kalian inginkan layaknya text editor lainnya.

### Normal Mode

Kalian akan menghabiskan sebagian besar dari waktu kalian di dalam Normal Mode. Mode ini digunakan untuk navigasi di dalam file teks yang sedang kalian edit.

Salah satu hal yang membuat Vim unik adalah alih alih menggunakan arrow-keys, Vim menggunakan HJKL. Hal ini dikarenakan [alasan historis](http://www.catonmat.net/blog/why-vim-uses-hjkl-as-arrow-keys/).
TLDR: letak arrow keys pada keyboard jaman dulu berada di tempat yang sama seperti tombol HJKL.

Kalian dapat menggunakan H untuk bergerak ke kiri, J untuk bergerak ke bawah, K untuk bergerak ke atas, dan L untuk bergerak ke kanan.

### Command Mode

Untuk masuk ke dalam Command Mode, cukup tekan <kbd>:</kbd> dari Normal Mode. Disini kalian dapat menulis berbagai macam command seperti `:quit`, `:write`, dan masih banyak lagi.

Sebagai contoh, untuk keluar dari Vim tanpa menyimpan file yang sudah kalian edit, cukup masuk ke Normal Mode terlebih dahulu dengan cara menekan <kbd>Esc</kbd> lalu ketik `:q` lalu tekan <kbd>Enter</kbd>.
```

2022-02-05 10:09 UTC, aldy505 commented on content/apa-itu-vim-secara-singkat.md
> +- Macos: bisa menggunakan unduh aplikasi atau pun mengetik di terminal
meanwhile CentOS dan Alpine menangis di pojokan

2022-02-05 12:00 UTC, afman42 commented on content/apa-itu-vim-secara-singkat.md
> +cover: https://1.bp.blogspot.com/-gl_s6BL9y34/XVeO7mNRChI/AAAAAAAABEI/wQ554bkHgs41eGC-1Ni-xmOPrm4n6ajWACLcBGAs/s1600/Vim_logo.png
iya om

2022-02-05 12:04 UTC, afman42 commented on content/apa-itu-vim-secara-singkat.md
> +Vim dikenal text editor di terminal dengan distribusi di sistem operasi windows,macos,dan linux. Aplikasi nya ringan dengan sekitar `~10mb` dan website nya pun belum berubah. Apakah vim powerfull unt
saya ganti dulu kak

2022-02-05 12:08 UTC, afman42 commented on content/apa-itu-vim-secara-singkat.md
> +copy satu baris maka diperlukan `yy` dan jika paste diperlukan `p`. untuk menyimpan atau save file maka perlu `Shift+:` dan `w` atau pun dari keluar vim bisa menggunkan `:q`
oke kak.

2022-02-05 13:14 UTC, afman42 commented
tolong di cek kak @elianiva , @aldy505 dan om @ronnygunawan

2022-02-05 13:15 UTC, aldy505 approved these changes
well done

2022-02-05 15:11 UTC, elianiva requested changes
Semua yg berhubungan sama nama key di keyboard (`ctrl+v`, `shift`, `I`, `v`, dll) diganti aja pake `<kbd>` biar bisa jadi kaya gini: <kbd>Ctrl+v</kbd>, <kbd>I</kbd>, <kbd>v</kbd>, dll.

2022-02-05 15:11 UTC, elianiva commented on content/apa-itu-vim-secara-singkat.md
> +  - `b` - berada di depan kata
```suggestion
  - `e` - bergerak ke depan sebanyak 1 kata dan berhenti di akhir kata tersebut
  - `b` - berpindah ke belakang sebanyak 1 kata dan berhenti di awal kata tersebut
```

2022-02-05 15:11 UTC, elianiva commented on content/apa-itu-vim-secara-singkat.md
> +  Dalam Insert Mode, kita bisa menuliskan atau mengedit text didalam VIM. Dan akses ke dalam yaitu masuk Normal Mode terlebih dahulu. Bisa juga seperti text editor pada umumnya: _enter_, _backspace_,
ini diwrap aja pake `<kbd>` biar nanti di blognya jadi kek icon keyboard
jadi `<kbd>enter</kbd>`, dll

2022-02-05 15:11 UTC, elianiva commented on content/apa-itu-vim-secara-singkat.md
> +  - `A` - masuk ke Insert Mode menuju ke akhir huruf satu baris
```suggestion
  - `i` - masuk ke Insert Mode, kursor akan berada di sebelah kiri dari huruf sekarang
  - `a` - masuk ke Insert Mode, kursor akan berada di sebelah kanan dari huruf sekarang
  - `I` - masuk ke Insert Mode, kursor akan berada di awal baris
  - `A` - masuk ke Insert Mode, kursor akan berada di akhir baris
```

2022-02-05 15:11 UTC, elianiva commented on content/apa-itu-vim-secara-singkat.md
> +  Dalam Visual Mode, untuk menyeleksi text atau huruf. Dan akses ke Visual Mode yaitu masuk Insert Mode. Halnya seperti _delete_/_cut_/_copy_. Berikut contohnya:
```suggestion
  Visual Mode digunakan untuk menyeleksi text atau huruf. Cara mengakses Visual Mode yaitu dengan cara menekan tombol `v`. Berikut contohnya:
```

2022-02-05 15:11 UTC, elianiva commented on content/apa-itu-vim-secara-singkat.md
> +  - `Shift+v` - masuk ke Visual Mode dan menyeleksi per baris
```suggestion
  - <kbd>v</kbd> - masuk ke Visual Mode dan menyeleksi per karakter
  - <kbd>Shift+v</kbd> - masuk ke Visual Line Mode dan menyeleksi per baris
  - <kbd>Ctrl+v</kbd> - masuk ke Visual Block Mode dan menyeleksi per _block_ 
```

2022-02-05 15:11 UTC, elianiva commented on content/apa-itu-vim-secara-singkat.md
> +  Dan juga di gabung perintah tersebut menjadi:
```suggestion
  Perintah diatas dapat digabung menjadi:
```

2022-02-05 15:11 UTC, elianiva commented on content/apa-itu-vim-secara-singkat.md
> +  Di dalam _VIM_ tersedia perintah tertulis yang sudah ada. Dan bisa di jalankan terminal seperti berikut:
```suggestion
  Di dalam Vim tersedia berbagai macam perintah atau _command_ yang dapat kita jalankan. Contoh:
```

2022-02-06 07:45 UTC, afman42 commented
cek lagi kak @elianiva dan om @ronnygunawan

2022-02-06 12:21 UTC, ronnygunawan approved these changes

2022-02-06 12:30 UTC, elianiva approved these changes

2022-02-06 12:31 UTC, merged